project:
  type: book

book:
  title: "AI for ecologists: a toolkit"
  
  author: 
  
    - name: "Sakina-Dorothée Ayata"
      orcid: "0000-0003-3226-9779"
      url: "https://orcid.org/0000-0003-3226-9779"
      affiliations: 
        - name: LOCEAN, Sorbonne Université
          url: "https://www.normalesup.org/~ayata/"
  
    - name: "Léo Blondel"
      orcid: "0000-0003-2276-4821"
      url: "https://orcid.org/0000-0003-2276-4821leo blondel ai
      "
      affiliations: 
        - name: founder of ailen.club
          url: "https://www.alien.club/"
          
    - name: "Camille Coux"
      orcid: "0000-0002-6346-9194"
      url: "https://orcid.org/0000-0002-6346-9194"
      affiliations: 
        - name: FRB-CESAB
          url: "https://www.fondationbiodiversite.fr/en/membre/camille-coux/"
          
          
    - name: "Dimitri Justeau-Allaire"
      orcid: "0000-0003-4129-0764"
      url: "https://orcid.org/0000-0003-4129-0764"
      affiliations: 
        - name: IRD, AMAP
          url: "https://dimitri-justeau.github.io/"
          
          
    - name: "Maximilien Servajean"
      orcid: "0000-0002-9426-2583"
      url: "https://orcid.org/0000-0002-9426-2583"
      affiliations: 
        - name: LIRMM
          url: "https://maximiliense.github.io/"
          
          
    - name: "Paul Tresson"
      orcid: "0000-0002-1275-4673"
      url: "https://orcid.org/0000-0002-1275-4673"
      affiliations: 
        - name: IRD, AMAP
          url: "https://amap.cirad.fr/fr/index.php"
      
  date: today
  description:  |
    FRB-CESAB training course
    <br /><br />
    <a href="https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/develop-skills/biodiversity-data-management/">
      <img class="logo" src="https://github.com/ai-ecol/AI-ecol/tree/main/images/banner-ia.png" style="width: 100%;" />
    </a>

  favicon: images/logo-biodiv-ia-si.png
  
  sidebar: 
    style: "docked"
    collapse-level: 1

  page-footer: 
    left: "&copy; CC-By [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/ai-ecol/ai-ecol.github.io/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true
  
  reader-mode: false
  search: false

  chapters:
    - index.qmd
    - part: "Prerequisites"
      chapters: 
        - chapters/setting-up-r.qmd
    - part: "Courses"
      chapters: 
        - chapters/coming-soon.qmd
    - part: "Exercises"
      chapters: 
        - chapters/coming-soon.qmd
    - part: "Resources"
      chapters: 
        - chapters/coming-soon.qmd

format:
  html:
    theme: [cosmo, css/styles.css]
    code-copy: true
    code-line-numbers: false
