project:
  type: book

book:
  title: "AI for ecologists: a toolkit"
  
  author: 
  
    - name: "Léo Blondel"
      orcid: "0000-0003-2276-4821"
      url: "https://orcid.org/0000-0003-2276-4821"
      affiliations: 
        - name: founder of ailen.club, Montpeliler
          url: "https://www.alien.club/"

          
    - name: "Dimitri Justeau-Allaire"
      orcid: "0000-0003-4129-0764"
      url: "https://orcid.org/0000-0003-4129-0764"
      affiliations: 
        - name: IRD, AMAP, Montpellier
          url: "https://dimitri-justeau.github.io/"
          
          
    - name: "Maximilien Servajean"
      orcid: "0000-0002-9426-2583"
      url: "https://orcid.org/0000-0002-9426-2583"
      affiliations: 
        - name: LIRMM, CNRS, Montpellier
          url: "https://maximiliense.github.io/"
          
          
    - name: "Paul Tresson"
      orcid: "0000-0002-1275-4673"
      url: "https://orcid.org/0000-0002-1275-4673"
      affiliations: 
        - name: IRD, AMAP, Montpellier
          url: "https://amap.cirad.fr/fr/index.php"


    - name: "Benjamin Bourel"
      orcid: "0000-0001-8312-5471"
      url: "https://orcid.org/0000-0001-8312-5471"
      affiliations:
        - name: INRIA, University of Montpellier, LIRMM, CNRS
          url: "https://www-sop.inria.fr/members/Benjamin.Bourel"


    - name: "Margot Challand"
      orcid: "0000-0001-6681-9906"
      url: "https://orcid.org/0000-0001-6681-9906"
      affiliations:
        - name: Institut Agro Montpellier
    
    - name: "Titouan Lorieul"
      orcid: "0000-0001-5228-9238"
      url: "https://orcid.org/0000-0001-5228-9238"
      affiliations:
        - name: Institut Agro Montpellier


    - name: "Camille Coux"
      orcid: "0000-0002-6346-9194"
      url: "https://orcid.org/0000-0002-6346-9194"
      affiliations: 
        - name: FRB-CESAB
          url: "https://www.fondationbiodiversite.fr/en/membre/camille-coux/"


    - name: "Romain Frelat"
      orcid: "0000-0002-8631-4398"
      url: "https://orcid.org/0000-0002-8631-4398"
      affiliations: 
        - name: FRB-CESAB
          url: "https://www.fondationbiodiversite.fr/en/membre/romain-frelat/"
      

  date: today
  description:  |
    FRB-CESAB training course
    <br /><br />
    <a href="https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/develop-skills/ia-pour-les-ecologues/">
      <img class="logo" src="https://raw.githubusercontent.com/AI-ecol/AI-ecol.github.io/main/images/banner-ia.png" style="width: 100%;" />
    </a>

  favicon: images/logo-biodiv-ia-si.png
  
  sidebar: 
    style: "docked"
    collapse-level: 1

  page-footer: 
    left: "&copy; CC-By [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/ai-ecol/ai-ecol.github.io/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true
  
  reader-mode: false
  search: false

  chapters:
    - index.qmd
    - part: "Courses"
      chapters: 
        - chapters/day1-courses.qmd
        - chapters/day2-courses.qmd
        - chapters/day3-courses.qmd
        #- chapters/day4-courses.qmd
        #- chapters/day5-courses.qmd
    - part: "Exercises"
      chapters: 
        - chapters/day1-colab-notebooks.qmd
        - chapters/day2-colab-notebooks.qmd
        - chapters/day3-colab-notebooks.qmd
        # - chapters/day4-colab-notebooks.qmd
        # - chapters/day5-colab-notebooks.qmd
    - part: "Resources"
      chapters: 
        - chapters/coming-soon.qmd

format:
  html:
    theme: [cosmo, css/styles.css]
    code-copy: true
    code-line-numbers: false
